### ISSUE TITLE
执行签到失败

### ISSUE THREAD

**Issue by chinesepy** [SamuNatsu/skland-daily-attendance-shell#2]
登录成功但，日志提示如下

```
2024/08/06 19:11:27 | stderr | jq: parse error: Invalid numeric literal at line 1, column 10
2024/08/06 19:11:27 | stderr | jq: parse error: Invalid numeric literal at line 1, column 10
2024/08/06 19:11:27 | stdout | [2024-08-06T19:11:27+0800] [    9] [ INFO] 森空岛鉴权成功
2024/08/06 19:11:26 | stdout | [2024-08-06T19:11:26+0800] [    9] [ INFO] OAuth 登陆成功
2024/08/06 19:11:26 | stdout | [2024-08-06T19:11:26+0800] [    9] [ INFO] 正在处理账号 #1
2024/08/06 19:11:26 | stdout | [2024-08-06T19:11:26+0800] [    1] [ INFO] 计划任务启动
```

**Comment by chinesepy** [comment]
是docker 环境运行的，Docker compose按照提供的方式编写。先前一个月一直稳定运行，今天突然提示失败

**Comment by SamuNatsu** [comment]
问题已发现，正在尝试修复

访问请求疑似被阿里云拦截了，理由是对网站造成安全威胁  
在服务器上触发了此问题，但是本地机器运行正常，感觉是 yj 对机房 IP 下手了

问题解决的概率感觉不大（  
只能多试几次（

**Comment by chinesepy** [comment]
> 问题已发现，正在尝试修复
> 
> 访问请求疑似被阿里云拦截了，理由是对网站造成安全威胁 在服务器上触发了此问题，但是本地机器运行正常，感觉是 yj 对机房 IP 下手了
> 
> 问题解决的概率感觉不大（ 只能多试几次（

但是我是在家里的NAS上运行的docker，我尝试开关了代理，问题依旧
用skland-daily-attendance 的github action倒是可以正常签到

**Comment by SamuNatsu** [comment]
> > 问题已发现，正在尝试修复
> > 访问请求疑似被阿里云拦截了，理由是对网站造成安全威胁 在服务器上触发了此问题，但是本地机器运行正常，感觉是 yj 对机房 IP 下手了
> > 问题解决的概率感觉不大（ 只能多试几次（
> 
> 但是我是在家里的NAS上运行的docker，我尝试开关了代理，问题依旧 用skland-daily-attendance 的github action倒是可以正常签到

所以说只能随缘（  
毕竟是阿里云拦截的（  
鬼知道怎样才算“不造成安全威胁”

**Comment by enpitsuLin** [comment]
https://github.com/Mon-ius/Docker-Warp-Socks  docker 环境应该可以通过使用这个来使用无限 ip 的 warp 代理来请求避免风控
