### ISSUE TITLE
手动执行返回错误

### ISSUE THREAD

**Issue by qq254950134** [SamuNatsu/skland-daily-attendance-shell#3]
手动输入SKLAND_TOKEN  ./attendance.sh命令后返回如下报错
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10

**Comment by SamuNatsu** [comment]
是森空岛检票阶段还是签到阶段？

**Comment by qq254950134** [comment]
开始签到任务
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
版面【纳斯特港】检票失败: 
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
版面【泡姆泡姆】检票失败: 
jq: parse error: Invalid numeric literal at line 1, column 10
版面【来自星辰】检票失败: 
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
jq: parse error: Invalid numeric literal at line 1, column 10
版面【明日方舟: 终末地】检票失败: 
jq: parse error: Invalid numeric literal at line 1, column 10
版面【开拓芯】检票失败: 
jq: parse error: Invalid numeric literal at line 1, column 10
版面【明日方舟】检票失败:

**Comment by qq254950134** [comment]
很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。 返回了这个信息

**Comment by SamuNatsu** [comment]
你看看项目 readme 罢

yj 现已经把这些自动化手段堵上 7788 了

最近疑似还上 IP 检测了，自动化系统已经差不多完蛋了

以后只能自己手动来了
